### ISSUE TITLE
Missat gem

### ISSUE THREAD

**Issue by ss223ck** [jb223cp/1DV450_jb223cp#1]
Behövde installera gem “tzinfo-data” för att kunna köra rake db:migrate

**Comment by Bejta** [comment]
Jag har inte behövt installera gem "tzinfo-data".
Vad som står i dokumentation [här](https://github.com/tzinfo/tzinfo/wiki/Resolving-TZInfo::DataSourceNotFound-Errors) är att : 

> This will typically occur if you are using Windows.

Jag ska uppdatera README.md och stänga issue.

**Comment by ss223ck** [comment]
Hej!

Okej, jag skrev bara vad jag behövde göra. Är själv inte så vass på RoR

2016-02-08 20:28 GMT+01:00 Jasmin Bejtovic notifications@github.com:
