### ISSUE TITLE
API-nyckel

### ISSUE THREAD

**Issue by ss223ck** [jb223cp/1DV450_jb223cp#2]
Det går att skapa en api-nyckel utan att behöva ange information i textfältet.

**Comment by Bejta** [comment]
Fixat!
I modellen client finns följande två linjer för validering nu:
`validates :name, presence: {:message => "Enter the name of your client"}, uniqueness: true
  validates  :url, presence: {:message => "Enter a url of your client"}, uniqueness: true
`

**Comment by 1dv450** [comment]
Bra!
