### ISSUE TITLE
Admins behörigheter

### ISSUE THREAD

**Issue by ss223ck** [jb223cp/1DV450_jb223cp#3]
Admin kan inte ta bort applikationer bara avaktivera och ta bort användare.

**Comment by Bejta** [comment]
I kravspecifikation står:

> En sida där den inloggade administratören kan ta bort(revoke) befintliga applikationer

Det står _revoke_ i parantes, och jag har uppfattat att man kan avaktivera ELLER ta bort användare. Jag har implementerad avaktivering för det känns mer lämpligt (t.ex. om man ska implementera prenumeneringar på tjänsten, så att administratör kan avavktivera api-key om användare inte betalat, och sen återaktivera om betalning är genomfört)

**Comment by ss223ck** [comment]
Ja du kanske har rätt, det är en bra implementation. Jag kan tänka mig att
en ideal applikation har båda dom funktionerna!

2016-02-08 20:59 GMT+01:00 Jasmin Bejtovic notifications@github.com:
