### ISSUE TITLE
Bugg för admins

### ISSUE THREAD

**Issue by ss223ck** [jb223cp/1DV450_jb223cp#7]
Bugg: skapar man en ny admin kan man ta bort det adminkontot i adminvyn. Väljer man att ta bort sitt konto krashar applikationen. Kollar man i vyn testar du på att användarnamnet är ”admin” när du kanske borde testa på egenskapen admin som klassen user har. Eller möjligtvis att man testar på administratören som är inloggad och då inte visar just användaren man är inloggad som. Det kan du enkelt göra genom att testa vilket userid du satt på sessionen och jämföra det i vyn istället för:
<% if u.username != 'admin'%> kan man använda <% if session[:userid] != u.userid %>

**Comment by Bejta** [comment]
Jag har gjort precis så, har testat och det funkar.
